name: NuGet Publish

on:
  release:
    types: [created]

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --include-symbols

      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push **/*.nupkg \
          --api-key $NUGET_API_KEY \
          --skip-duplicate

